# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

image: node:6.9.4
pipelines:
  default:
    - step:
        script:
          - apt-get update -y
          - apt-get install -y librsvg2-bin
          - npm install
          - npm run build
          - npm run update-example
